---
- name: fetch a linux distro name/version
  shell: cat /etc/issue
  register: etc_issue

- name: printing hostnames together with registered variables.
  debug: 
    msg: "HOSTNAME: {{ ansible_hostname }} ISSUE: {{ etc_issue.stdout }}" 