---
# Create a inventory file with four groups, 
# each provisioning VM should be in separate group and 
# group named iaas what should include childrens from two first groups;
all:
  children:
    iaas_1:
      hosts: 
        first:
          include_vars: ./pw_vars/first.yml

    iaas_2:
      hosts: 
        second:
          include_vars: ./pw_vars/second.yml

    iaas_3:
      hosts: 
        third:
          include_vars: ./pw_vars/third.yml

    iaas_4:
      hosts: 
        fourth:
          include_vars: ./pw_vars/fourth.yml

    iaas:
      children:
        iaas_1:
        iaas_2:
